name: part_generator
version: 0.0.1+
author: "takyam <takayuki.yamaguch.m@gmail.com>"
homepage: https://github.com/takyam-git/part_generator
description: "Generate 'part **' list and output to console."
dependencies:
  analyzer: ">=0.22.4 <1.0.0"
  glob: ">=1.0.3 <2.0.0"
  args: ">=0.12.1 <1.0.0"
  path: ">=1.3.0 <2.0.0"
dev_dependencies:
  unittest: ">=0.11.1+1 <1.0.0"